<?php

namespace App\Classes\enums;

abstract class OrderOperationsEnum extends Enum
{
    const REGISTER = "REGISTER";
    const UPDATE_REGISTERED = "UPDATE_REGISTERED";
    const ASSIGN_TO_TECH_MANAGER = "ASSIGN_TO_TECH_MANAGER";
    const ASSIGN_TO_OPTIMIZER = "ASSIGN_TO_OPTIMIZER";
    const UPDATE_CHECKLIST_STATUS = "UPDATE_CHECKLIST_STATUS";
    const UPDATE_CLIENT_KEYWORDS = "UPDATE_CLIENT_KEYWORDS";
    const CONFIRM_CLIENT_KEYWORDS = "CONFIRM_CLIENT_KEYWORDS";
    const COMPLETE = "COMPLETE";
    const ADD_EXCEPTIONAL_CHECKLIST = "ADD_EXCEPTIONAL_CHECKLIST";
}